load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "unique_ptr",
    srcs = ["smart_ptr.cc"],
)

cc_binary(
    name = "smart_shared_ptr",
    srcs = ["smart_shared_ptr.cc"],
)