load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "lc10",
    srcs = ["lc10.cc"],
)

cc_binary(
    name = "lc12",
    srcs = ["lc12.cc"],
)

cc_binary(
    name = "lc13",
    srcs = ["lc13.cc"],
)

cc_binary(
    name = "lc15",
    srcs = ["lc15.cc"],
)